<!DOCTYPE html>
<html>
<head>
       <!-- initialising the style sheet-->
	   <link rel="stylesheet" type="text/css" href="css/Main.css" media="all" />   
	   <link rel="stylesheet" type="text/css" href="css/Comments.css" media="all" />  
</head>
<body>
<div class="gridcontainer">
    <div class="gridwrapper">
        <div class="gridbox gridheader">
            <div class="header">
		    <!-- Header -->
			<?php include("Include/Header.html");?>
            </div>
        </div>
        <div class="gridbox gridmenu">
		    <!-- Navigation menu -->            
			<?php include("Include/navigation.php");?> 
        </div>
        <div class="gridbox gridmain">
            <div class="main">
            <!--body-->
			<h1> Frequent Asked Questions</h1>
			<P> Here is a list of the most asked questions </p>
    <!--  Questions example -->  
<div class="tooltips-gray">Why can't I log into my account?<div></div></div>
<!-- end the q-->

<!-- Answer 1 -->
<div class="clean-gray"> This is usually due to a problem with the password or e-mail address you're entering. If you've tried various combinations and spellings but still can't log into your account, use the password reset botton</div>
<!-- end answer 1-->      

<div class="tooltips-gray">If I want to close my account, what do I need to do?<div></div></div>
<!-- end the q-->

<!-- Answer  -->
<div class="clean-gray"> 
To prepare for closing your Selling on Amazon account, make sure to prepare the following items:
- Fulfill any outstanding orders.
- Cancel all of your listings to remove them from sale on the Amazon website
Note:
The closure of your seller account is a permanent action. 

</div>
<!-- end answer -->  
        
    <div class="tooltips-gray">What should I do if I can't find what I want to sell in the catalog?<div></div></div>
<!-- end the q-->

<!-- Answer 1 -->
<div class="clean-gray"> If you want to sell an item but it does not currently exist in our retail catalog, you may be able to create a page for it using the Add a Product tool in your seller account. Once a page has been created for the product, you can list your copy of the item on it.</div>
<!-- end answer 1-->       
        
      <div class="tooltips-gray">What is a product detail page?<div></div></div>
<!-- end the q-->

<!-- Answer 1 -->
<div class="clean-gray"> A product detail page is the place where customers read details about a product for share on the website.
 It includes the product image, price, description, customer reviews, ordering options, and the link to view offers from all sellers.</div>
<!-- end answer 1-->    

          
      <div class="tooltips-gray">How will I know when I have to return a book?<div></div></div>
<!-- end the q-->

<!-- Answer 1 -->
<div class="clean-gray"> 
When an order is placed and the payment method has been authorized, we will be given a period of time.
When you are 48 hours away from the due time we will send an email to you.
</div>
<!-- end answer 1-->
     
            </div>
        </div>
 
 
        <div class="gridbox gridfooter">
            <div class="footer">
            <!-- footer -->
			<?php include("Include/footer.html");?>
            </div>
        </div>
    </div>
</div>
</body>
</html>
