@extends('layouts.master')

@section('title', 'Terms and Conditions')

@section('content')
    @parent
    <div id="terms">
    <h2>1. Introduction</h2>
	<p>
	1.1	These terms and conditions shall govern your use of our website.<br>
	1.2	By using our website, you accept these terms and conditions in full; accordingly, if you disagree with these terms and conditions or any part of these terms and conditions, you must not use our website.<br>
	1.3	If you [register with our website, submit any material to our website or use any of our website services], we will ask you to expressly agree to these terms and conditions.<br>
	1.4	You must be at least [18] years of age to use our website; and by using our website or agreeing to these terms and conditions, you warrant and represent to us that you are at least [18] years of age.<br>
	</p>

	<h2>2. Copyright notice</h2>
	<p>
	2.1	Copyright (c) [5 year(s) of first publication].<br>
	2.2	Subject to the express provisions of these terms and conditions:<br>
	(a)	we, together with our licensors, own and control all the copyright and other intellectual property rights in our website and the material on our website; and<br>
	(b)	all the copyright and other intellectual property rights in our website and the material on our website are reserved.<br>
	</p>

	<h2>3. Licence to use website</h2>
	<p>
	3.1	You may:<br>
	(a)	view pages from our website in a web browser;<br>
	(b)	download pages from our website for caching in a web browser;<br>
	(c)	print pages from our website;<br>
	(d)	use our website services by means of a web browser, subject to the other provisions of these terms and conditions.<br>
	3.2	Except as expressly permitted by Section 4.1 or the other provisions of these terms and conditions, you must not download any material from our website or save any such material to your computer.<br>
	3.3	You may only use our website for [your own personal and business purposes], and you must not use our website for any other purposes.<br>
	3.4	Except as expressly permitted by these terms and conditions, you must not edit or otherwise modify any material on our website.<br>
	3.5	We reserve the right to restrict access to areas of our website, or indeed our whole website, at our discretion; you must not circumvent or bypass, or attempt to circumvent or bypass, any access restriction measures on our website.
	</p>
	<h2>4. Acceptable use</h2>
	<p>
	4.1	You must not:<br>
	(a)	use our website in any way or take any action that causes, or may cause, damage to the website or impairment of the performance, availability or accessibility of the website;<br>
	(b)	use our website in any way that is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity;<br>
	(c)	use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software;<br>
	(d)	conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to our website without our express written consent;<br>
	(e)	access or otherwise interact with our website using any robot, spider or other automated means;<br>
	(f)	violate the directives set out in the robots.txt file for our website; or<br>
	(g)	use data collected from our website for any direct marketing activity (including without limitation email marketing, SMS marketing, telemarketing and direct mailing).<br>
	4.2	You must not use data collected from our website to contact individuals, companies or other persons or entities.<br>
	4.3	You must ensure that all the information you supply to us through our website, or in relation to our website, is [true, accurate, current, complete and non-misleading.
	</p>
    <h2>5. Cancellation and suspension of account</h2>
    <p>
	5.1	We may:<br>
	(a)	suspend your account<br>
	(b)	cancel your account<br>
	(c)	edit your account details at any time in our sole discretion without notice or explanation.<br>
	5.2	You may cancel your account on our website using your account control panel on the website.
	</p>
</div>

@endsection

